### ISSUE TITLE
Windows build fails if --with_examples is not offered as an option

### ISSUE THREAD

**Issue by philippe72** [Dudi119/cppKin#84]
When I try to build the library for windows and I do not include the command --with_examples the build fails because it cannot find the boost dependencies. Only when including --with_examples the boost dependencies are downloaded.

I propose that you add this to the instructions for windows?

**Comment by Dudi119** [comment]
Hi Philippe, you are correct, i'm working on a fix for resolving the example requirement issue. running tests now.

thanks.

**Comment by Dudi119** [comment]
addressed via #86.

**Comment by philippe72** [comment]
Awesome! I will test this later today on my system

**Comment by Dudi119** [comment]
thanks, see if its working fine and i will close the issue.

**Comment by philippe72** [comment]
Tested with VS2013 with command 'cppkin.bat install --vc_version=xx' and it worked fine!

**Comment by Dudi119** [comment]
great, closing the issue.
