### ISSUE TITLE
Windows build fails for Visual Studio 2015 (and up)

### ISSUE THREAD

**Issue by philippe72** [Dudi119/cppKin#85]
VS2013 and VS2017 build fine (as long as I also pass the --with_examples flag to the build script, see my other issue)

However VS2015 fails due to 'error LNK2019: unresolved external symbol __imp____iob_xxx reference' errors. Best I was able to determine so far as to what may be the cause of this issue is [this](https://stackoverflow.com/questions/30412951/unresolved-external-symbol-imp-fprintf-and-imp-iob-func-sdl2) issue on StackOverflow that mentions a breaking change in VS2015 (but since VS2017 builds fine apparently they did some sort of fix for it later).

I propose to mention this in the documentation?

**Comment by Dudi119** [comment]
Hi Philippe, you are correct, i'm working on a fix for resolving the example requirement issue. running tests now.

regarding VS2015, i will attempt to run a local build of it, see if i can reproduce the issue you mentioned.

and thank you for pointing those issues out.

**Comment by philippe72** [comment]
Just to correct my previous statement that it was building fine for VS2017: I apparently did something incorrectly, because when I specifically pass --vc_version=15 to the build script it fails with the same errors as VS2015

**Comment by Dudi119** [comment]
ok, i just released a fix, as of now only visual studio 2015 (VC++ 14.0) and visual studio 2013 (VC++ 12.0) are tested and supported, i also updated the documents to indicate that.
i will add a support for VC++ 14.1 (Visual studio 2017) in the coming days.
fix #87 

btw, --vc_version supports two values - **12** for visual studio 2013 and **14** for visual studio 2015.
i will update the batch script to indicate that and force it if necessary.

**Comment by philippe72** [comment]
Hi, sorry I haven't been able to test yet. Hope to get around to this tomorrow and I will let you know

**Comment by Dudi119** [comment]
Ok, great, let me know and I will close the issue if all goes well.

**Comment by philippe72** [comment]
Hi, apologies for not getting around to testing sooner. I downloaded and build the latest version for VS2015 succesfully.

Many thanks for fixing this!

**Comment by Dudi119** [comment]
ok, great, thank you for reporting it :).
closing the issue. i will add support for VS2017 in the future.
